name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ALSA dev libraries
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build

      - name: Format Check (cargo fmt)
        run: cargo fmt --all -- --check

      - name: Lint (cargo clippy)
        run: cargo clippy --all -- -D warnings

      - name: Run Tests
        run: cargo test --all
